### ISSUE TITLE
如果我用的是框架做开发，然后引入了这个框架的整个css,编译很久都不成功

### ISSUE THREAD

**Issue by w530385371** [weixin/WeFlow#17]
例如：引入了mui.less,文件有85k,dev可以运行，但是点击编译，就一直这样，不动了，如果把这个mui.less去掉就可以正常编译

![qq 20160627103618](https://cloud.githubusercontent.com/assets/6317593/16367152/345424cc-3c53-11e6-9f83-62d5426bffda.png)

![qq 20160627103741](https://cloud.githubusercontent.com/assets/6317593/16367174/5d2809ea-3c53-11e6-97e0-74f179bee036.png)

**Comment by hzlzh** [comment]
检查一下 `mui.less` 是否有兼容性写法问题，或者语法错误。
如果方便可以把代码发到 [Gist](https://gist.github.com/)来一起分析。

**Comment by w530385371** [comment]
我改成txt了,方便上传
[mui.txt](https://github.com/weixin/WeFlow/files/334056/mui.txt)

**Comment by hzlzh** [comment]
````css
.mui-spinner:after
{
    display: block;

    width: 100%;
    height: 100%;

    content: '';

    background-image: url('data:image/svg+xml;charset=utf-8,<svg viewBox=\'0 0 120 120\' xmlns=\'http://www.w3.org/2000/svg\' xmlns:xlink=\'http://www.w3.org/1999/xlink\'><defs><line id=\'l\' x1=\'60\' x2=\'60\' y1=\'7\' y2=\'27\' stroke=\'%236c6c6c\' stroke-width=\'11\' stroke-linecap=\'round\'/></defs><g><use xlink:href=\'%23l\' opacity=\'.27\'/><use xlink:href=\'%23l\' opacity=\'.27\' transform=\'rotate(30 60,60)\'/><use xlink:href=\'%23l\' opacity=\'.27\' transform=\'rotate(60 60,60)\'/><use xlink:href=\'%23l\' opacity=\'.27\' transform=\'rotate(90 60,60)\'/><use xlink:href=\'%23l\' opacity=\'.27\' transform=\'rotate(120 60,60)\'/><use xlink:href=\'%23l\' opacity=\'.27\' transform=\'rotate(150 60,60)\'/><use xlink:href=\'%23l\' opacity=\'.37\' transform=\'rotate(180 60,60)\'/><use xlink:href=\'%23l\' opacity=\'.46\' transform=\'rotate(210 60,60)\'/><use xlink:href=\'%23l\' opacity=\'.56\' transform=\'rotate(240 60,60)\'/><use xlink:href=\'%23l\' opacity=\'.66\' transform=\'rotate(270 60,60)\'/><use xlink:href=\'%23l\' opacity=\'.75\' transform=\'rotate(300 60,60)\'/><use xlink:href=\'%23l\' opacity=\'.85\' transform=\'rotate(330 60,60)\'/></g></svg>');
    background-repeat: no-repeat;
    background-position: 50%;
    background-size: 100%;
}

.mui-spinner-white:after
{
    background-image: url('data:image/svg+xml;charset=utf-8,<svg viewBox=\'0 0 120 120\' xmlns=\'http://www.w3.org/2000/svg\' xmlns:xlink=\'http://www.w3.org/1999/xlink\'><defs><line id=\'l\' x1=\'60\' x2=\'60\' y1=\'7\' y2=\'27\' stroke=\'%23fff\' stroke-width=\'11\' stroke-linecap=\'round\'/></defs><g><use xlink:href=\'%23l\' opacity=\'.27\'/><use xlink:href=\'%23l\' opacity=\'.27\' transform=\'rotate(30 60,60)\'/><use xlink:href=\'%23l\' opacity=\'.27\' transform=\'rotate(60 60,60)\'/><use xlink:href=\'%23l\' opacity=\'.27\' transform=\'rotate(90 60,60)\'/><use xlink:href=\'%23l\' opacity=\'.27\' transform=\'rotate(120 60,60)\'/><use xlink:href=\'%23l\' opacity=\'.27\' transform=\'rotate(150 60,60)\'/><use xlink:href=\'%23l\' opacity=\'.37\' transform=\'rotate(180 60,60)\'/><use xlink:href=\'%23l\' opacity=\'.46\' transform=\'rotate(210 60,60)\'/><use xlink:href=\'%23l\' opacity=\'.56\' transform=\'rotate(240 60,60)\'/><use xlink:href=\'%23l\' opacity=\'.66\' transform=\'rotate(270 60,60)\'/><use xlink:href=\'%23l\' opacity=\'.75\' transform=\'rotate(300 60,60)\'/><use xlink:href=\'%23l\' opacity=\'.85\' transform=\'rotate(330 60,60)\'/></g></svg>');
}
````

是 mui.less 里的这两行造成的， PostCSS 在处理的时候不识别这样的 svg 写法，建议参看这里进行改进，另外 tmt-workflow 里也会考虑集成：
https://github.com/ben-eb/postcss-svgo/issues/12
