### ISSUE TITLE
如何禁止自动生成图片 CSS 属性，width & height 等

### ISSUE THREAD

**Issue by xyyjk** [weixin/WeFlow#43]
#### 运行环境

- [x] 操作系统 & 版本：`macOS (10.11.6)`
- [x] WeFlow 版本： `v1.3.1`

#### 反馈具体描述：

rt , 有些时候是不希望自动添加 width & height 值的，如下图（尺寸已经在 `i[class^=task-item]` 选择器中定义好了）了解到是通过 `lazyimagecss` 来自动生成的，如何禁止？ 

### before - SCSS
![](http://i2.piimg.com/567571/97ecc0c7e0993934.png)
### after - CSS
![](http://i2.piimg.com/567571/90b05dec4cc3e7c2.png)

**Comment by xyyjk** [comment]
目前自行调整文件解决了
/Applications/WeFlow.app/Contents/Resources/app/src/_tasks/dev.js
/Applications/WeFlow.app/Contents/Resources/app/src/_tasks/dist.js

**Comment by hzlzh** [comment]
是的，默认开启了 https://github.com/weixin/gulp-lazyimagecss，目前不提供开关，这里我们讨论一下看是否有必要纳入规划。

另外，看你这里图片放在 `../slice` 目录下，是期望进行雪碧图合并吧，但是 **after**里的代码没有做雪碧图处理，建议使用官方 demo 里格式来书写一下试试。

````css
// 微信-分享 icon 模块
.mod-social-media{
	text-align: center;
}
.mod-social-media__list{

}
.mod-social-media__icon{
	width: 90px;
	height: 90px;
	display: inline-block;
	margin: 0 5px;
	background-color: #fff;
	.rounded(10px);
}
.mod-social-media__icon_share{
	background-image: url(../slice/mod-social-media/icon-share@2x.png);
}
.mod-social-media__icon_moment{
	background-image: url(../slice/mod-social-media/icon-moment@2x.png);
}
.mod-social-media__icon_favadd{
	background-image: url(../slice/mod-social-media/icon-favadd@2x.png);
}
.mod-social-media__icon_copy{
	background-image: url(../slice/mod-social-media/icon-copy@2x.png);
}
.mod-social-media__icon_refresh{
	background-image: url(../slice/mod-social-media/icon-refresh@2x.png);
}
````

via: https://github.com/weixin/tmt-workflow/blob/1.5.3/project/src/css/mod-social-media.less
